---
# tasks file for create_vpc_peering
- name: Get the VPC ID for default-vpc
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: default_vpc_net_facts

- name: "Create local VPC peering connection"
  ec2_vpc_peer:
    region: {{ ec2_region }}
    vpc_id: "{{ create_vpc.vpc.id }}"
    peer_vpc_id: "{{ default_vpc_net_facts.vpcs[0].id }}"
    state: present
  register: vpc_peer

- name: "Accept local VPC peering connection"
  ec2_vpc_peer:
    region: {{ ec2_region }}
    peering_id: "" 
    state: accept
  register: accept_peer
